s = set()
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 1: ")
s.add(int(n))

print(s)